# Generated by Django 5.0.3 on 2024-04-03 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("calories", models.CharField(max_length=120)),
                ("fats", models.CharField(max_length=120)),
                ("carbs", models.CharField(max_length=120)),
                ("proteins", models.CharField(max_length=120)),
                ("unsaturated_fats", models.CharField(max_length=120)),
                ("sugar", models.CharField(max_length=120)),
                ("salt", models.CharField(max_length=120)),
                ("portion", models.CharField(max_length=120)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api_menu.menu"
                    ),
                ),
            ],
        ),
    ]
