# Generated by Django 5.0.3 on 2024-04-03 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_menu", "0002_remove_product_menu_delete_menu"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["id"]},
        ),
        migrations.RenameField(
            model_name="product",
            old_name="title",
            new_name="name",
        ),
    ]
